/* Best Robux — autenticação única e resiliente. Nunca expõe service-role. */
(()=>{
 if(window.__BESTROBUX_AUTH_V4__)return; window.__BESTROBUX_AUTH_V4__=true;
 const URL='https://anlwpqwjjswkqncltcdl.supabase.co',KEY='sb_publishable_r3GoKwcOEaXySt7fFOM_0A_rNOc7Mq7',STORAGE='bestrobux-auth';
 const race=(p,ms=10000)=>{let id;return Promise.race([p,new Promise((_,rej)=>id=setTimeout(()=>rej(new Error('TIMEOUT')),ms))]).finally(()=>clearTimeout(id))};
 const client=()=>{if(window.bestRobuxSupabase)return window.bestRobuxSupabase;if(!window.supabase?.createClient)return null;return window.bestRobuxSupabase=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:STORAGE,storage:window.localStorage,flowType:'pkce'}})};
 async function session(force=false){const c=client();if(!c)throw new Error('SUPABASE_UNAVAILABLE');if(force)try{const r=await race(c.auth.refreshSession());if(r.data?.session)return r.data.session}catch{}try{const r=await race(c.auth.getSession());if(r.data?.session)return r.data.session}catch{}try{const r=await race(c.auth.refreshSession());if(r.data?.session)return r.data.session}catch{}return null}
 window.bestRobuxGetSession=()=>session(false);
 window.bestRobuxAuthReady=(async()=>{const s=await session(false);if(!s?.user?.id)return s;try{const r=await race(client().from('profiles').select('account_status,suspended_until').eq('id',s.user.id).maybeSingle(),5000),p=r.data;if(p?.account_status==='BANNED'||(p?.account_status==='SUSPENDED'&&p.suspended_until&&new Date(p.suspended_until)>new Date())){await client().auth.signOut();return null}}catch{}return s})();
 window.bestRobuxApi=async(path,options={})=>{let s=await session(false);if(!s)throw new Error('AUTH_REQUIRED');const run=async tok=>{const r=await race(fetch(path,{...options,cache:'no-store',headers:{...(options.headers||{}),Authorization:'Bearer '+tok,'Content-Type':'application/json'}}),20000),d=await r.json().catch(()=>({}));return{r,d}};let o=await run(s.access_token);if(o.r.status===401){s=await session(true);if(!s)throw new Error('AUTH_REQUIRED');o=await run(s.access_token)}if(!o.r.ok)throw new Error(o.d?.error||'REQUEST_FAILED');return o.d};
})();