export const config={runtime:'nodejs'};
import { createClient } from '@supabase/supabase-js';
const env=n=>{const v=process.env[n];if(!v)throw Error(`Missing ${n}`);return v};
const allowed=new Set(['profiles','direct_conversations','direct_messages','reports','support_tickets','support_messages','admin_audit_logs','admin_roles','site_settings','products','coupons']);
const filterable=['id','user_id','user_a','user_b','sender_id','ticket_id','conversation_id'];
const uuidList=v=>String(v||'').split(',').map(x=>x.trim()).filter(x=>/^[0-9a-f-]{36}$/i.test(x)).slice(0,1000);const isUuid=v=>/^[0-9a-f-]{36}$/i.test(String(v||''));
const client=()=>createClient(env('SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}});
async function actor(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const db=client();const {data:{user},error}=await db.auth.getUser(h.slice(7));if(error||!user)return null;const {data:row,error:re}=await db.from('admin_roles').select('role').eq('user_id',user.id).maybeSingle();if(re)throw re;if(!row?.role)return null;return {user,role:String(row.role).toUpperCase(),db}}
async function allUsers(db){let out=[],page=1;while(true){const {data,error}=await db.auth.admin.listUsers({page,perPage:1000});if(error)throw error;const users=data?.users||[];out.push(...users);if(users.length<1000)break;page++}return out}
async function post(req,res,a){const action=String(req.body?.action||'');const manager=['LIDER','ADMINISTRADOR'].includes(a.role);if(action==='notification'){if(!manager)return res.status(403).json({error:'Sem permissão.'});const title=String(req.body?.title||'').trim(),message=String(req.body?.message||'').trim(),type=String(req.body?.type||'info').trim()||'info';if(!title||!message)return res.status(400).json({error:'Título e mensagem são obrigatórios.'});let ids=req.body?.mode==='all'?(await allUsers(a.db)).map(u=>u.id):(Array.isArray(req.body?.userIds)?req.body.userIds.map(String).filter(Boolean):[]);ids=[...new Set(ids)];if(!ids.length)return res.status(400).json({error:'Selecione pelo menos um usuário.'});const {error}=await a.db.from('notifications').insert(ids.map(user_id=>({user_id,title,message,type})));if(error)throw error;await a.db.from('admin_audit_logs').insert({admin_id:a.user.id,action:'BROADCAST_NOTIFICATION',metadata:{type,mode:req.body?.mode==='all'?'all':'selected',sent:ids.length,role:a.role},created_at:new Date().toISOString()});return res.json({ok:true,sent:ids.length,role:a.role})}if(action==='set_role'||action==='remove_role'){if(a.role!=='LIDER')return res.status(403).json({ok:false,error:'Somente o Líder pode gerenciar cargos.'});const target=String(req.body?.target||'');if(!isUuid(target)||target===a.user.id)return res.status(400).json({ok:false,error:'Usuário alvo inválido.'});if(action==='set_role'){const newRole=String(req.body?.role||'').toUpperCase();if(!['ADMINISTRADOR','SUPORTE','ATENDENTE'].includes(newRole))return res.status(400).json({ok:false,error:'Cargo inválido.'});const {data,error}=await a.db.from('admin_roles').upsert({user_id:target,role:newRole,created_by:a.user.id,created_at:new Date().toISOString()},{onConflict:'user_id'}).select('user_id,role,created_at').single();if(error)throw error;await a.db.from('admin_audit_logs').insert({admin_id:a.user.id,action:'SET_ADMIN_ROLE',metadata:{target_user_id:target,new_role:newRole},created_at:new Date().toISOString()});return res.json({ok:true,data,role:a.role})}const {data,error}=await a.db.from('admin_roles').delete().eq('user_id',target).select('user_id,role').maybeSingle();if(error)throw error;if(!data)return res.status(404).json({ok:false,error:'Este usuário não possui cargo administrativo.'});await a.db.from('admin_audit_logs').insert({admin_id:a.user.id,action:'REMOVE_ADMIN_ROLE',metadata:{target_user_id:target,old_role:data.role},created_at:new Date().toISOString()});return res.json({ok:true,data,role:a.role})}return res.status(400).json({error:'Ação administrativa inválida.'})}
export default async function handler(req,res){try{const a=await actor(req);if(!a)return res.status(403).json({error:'Acesso administrativo necessário.'});if(req.method==='POST')return post(req,res,a);if(req.method!=='GET')return res.status(405).json({error:'Método não permitido.'});const resource=String(req.query.resource||'');if(!allowed.has(resource))return res.status(400).json({error:'Recurso administrativo inválido.'});const limit=Math.min(Math.max(Number(req.query.limit)||500,1),1000);let q=a.db.from(resource).select('*');for(const original of filterable){if(req.query[original])q=q.eq(resource==='profiles'&&original==='user_id'?'id':original,String(req.query[original]))}if(req.query.ids){const ids=uuidList(req.query.ids);if(ids.length)q=q.in('id',ids)}if(req.query.user_ids){const ids=uuidList(req.query.user_ids);if(ids.length)q=q.in(resource==='profiles'?'id':'user_id',ids)}if(req.query.sender_ids){const ids=uuidList(req.query.sender_ids);if(ids.length)q=q.in('sender_id',ids)}const order=String(req.query.order||'created_at'),ascending=String(req.query.asc||'false')==='true';q=q.order(order,{ascending}).limit(limit);const {data,error}=await q;if(error)throw error;return res.status(200).json({data:Array.isArray(data)?data:[],role:a.role})}catch(e){console.error('admin-data',e);return res.status(500).json({ok:false,error:e?.message||'Erro interno.'})}}
