import { createClient } from '@supabase/supabase-js';
export const config={runtime:'edge'};
const response=(status,body)=>new Response(JSON.stringify(body),{status,headers:{'Cache-Control':'no-store, max-age=0','Content-Type':'application/json; charset=utf-8','X-Content-Type-Options':'nosniff'}});
const client=(url,key,token)=>createClient(url,key,{auth:{persistSession:false},global:token?{headers:{Authorization:`Bearer ${token}`}}:undefined});
export default async function handler(req){if(req.method!=='GET')return response(405,{error:'Método não permitido.'});try{
 const token=String(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token||token.length>8192||token.split('.').length!==3)return response(401,{error:'Faça login novamente.'});
 const url=process.env.SUPABASE_URL,service=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!service)return response(503,{error:'Serviço financeiro não configurado.'});
 const adminDb=client(url,service);const auth=await adminDb.auth.getUser(token);if(auth.error||!auth.data?.user)return response(401,{error:'Sua sessão expirou. Atualize a página e entre novamente.'});
 const uid=auth.data.user.id;const role=await adminDb.from('admin_roles').select('role').eq('user_id',uid).maybeSingle();if(role.error)throw role.error;if(!['LIDER','ADMINISTRADOR'].includes(String(role.data?.role||'').toUpperCase()))return response(403,{error:'Acesso administrativo insuficiente.'});
 const [accounts,withdrawals,med,checks]=await Promise.all([adminDb.from('wallet_accounts').select('user_id,balance,updated_at').order('updated_at',{ascending:false}).limit(1000),adminDb.from('wallet_withdrawals').select('id,user_id,amount,fee,status,created_at,updated_at').order('created_at',{ascending:false}).limit(100),adminDb.from('med_cases').select('id,user_id,source_type,source_id,amount,status,reason,justification,review_reason,created_at,updated_at').order('created_at',{ascending:false}).limit(100),adminDb.from('wallet_integrity_checks').select('id,user_id,recorded_balance,ledger_balance,difference,status,checked_at').order('checked_at',{ascending:false}).limit(100)]);
 for(const q of [accounts,withdrawals,med,checks])if(q.error)throw q.error;const a=accounts.data||[],w=withdrawals.data||[],m=med.data||[],c=checks.data||[];return response(200,{summary:{accounts:a.length,totalBalance:a.reduce((n,x)=>n+Number(x.balance||0),0),negativeAccounts:a.filter(x=>Number(x.balance)<0).length,pendingWithdrawals:w.filter(x=>['PENDING','PROCESSING'].includes(String(x.status).toUpperCase())).length,pendingMed:m.filter(x=>['AWAITING_JUSTIFICATION','UNDER_REVIEW'].includes(String(x.status).toUpperCase())).length,mismatches:c.filter(x=>x.status!=='OK').length},accounts:a,withdrawals:w,med:m,checks:c});
}catch(e){if(e?.message!=='AUTH')console.error('admin-wallet',e);return response(500,{error:'Não foi possível carregar o centro financeiro.'})}}