import { createClient } from '@supabase/supabase-js';
const json=(res,status,body)=>res.status(status).json(body);
const digits=v=>String(v||'').replace(/\D/g,'').slice(0,11);
function validCPF(v){const d=digits(v);if(d.length!==11||/^(\d)\1+$/.test(d))return false;let s=0;for(let i=0;i<9;i++)s+=+d[i]*(10-i);let r=(s*10)%11;if(r===10)r=0;if(r!==+d[9])return false;s=0;for(let i=0;i<10;i++)s+=+d[i]*(11-i);r=(s*10)%11;if(r===10)r=0;return r===+d[10]}
function env(n){const v=process.env[n];if(!v)throw Error(`Missing ${n}`);return v}
function validGamepassUrl(value){try{const u=new URL(value);if(u.protocol!=='https:'&&u.protocol!=='http:')return false;const host=u.hostname.toLowerCase();if(host!=='roblox.com'&&!host.endsWith('.roblox.com'))return false;return /game[- ]?pass|gamepass|passes/.test(u.pathname.toLowerCase())&&/\d+/.test(u.pathname)}catch{return false}}
function dbMessage(error){if(!error)return 'unknown database error';return [error.code,error.message,error.details,error.hint].filter(Boolean).join(' — ').slice(0,500)}
function misticHeaders(){return {'Content-Type':'application/json',ci:env('MISTICPAY_CLIENT_ID'),cs:env('MISTICPAY_CLIENT_SECRET')}}
export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{error:'Método não permitido.'});let stage='request';try{
 const auth=req.headers.authorization||'';if(!auth.startsWith('Bearer '))return json(res,401,{error:'Faça login para continuar.'});
 stage='authentication';const token=auth.slice(7),url=env('SUPABASE_URL'),anonKey=env('SUPABASE_ANON_KEY');
 const authClient=createClient(url,anonKey,{auth:{persistSession:false}});const {data:{user},error:authError}=await authClient.auth.getUser(token);if(authError||!user)return json(res,401,{error:'Sessão inválida. Entre novamente.'});
 stage='validation';const b=req.body||{},name=String(b.name||'').trim(),cpf=digits(b.cpf),email=String(b.email||'').trim().toLowerCase(),robloxUsername=String(b.robloxUsername||'').trim(),quantity=Number(b.quantity),type=b.type==='Robux Plus'?'Robux Plus':'Gamepass',gamepassUrl=String(b.gamepassUrl||'').trim(),confirmRobloxName=String(b.confirmRobloxName??b.robloxConfirm??'').trim();
 if(name.split(/\s+/).length<2)return json(res,400,{error:'Informe o nome completo.'});if(!validCPF(cpf))return json(res,400,{error:'Informe um CPF válido.'});if(email!==String(user.email||'').toLowerCase())return json(res,400,{error:'O e-mail do pedido deve ser o da conta.'});if(!/^[A-Za-z0-9_]{3,20}$/.test(robloxUsername))return json(res,400,{error:'Usuário do Roblox inválido.'});if(!Number.isInteger(quantity)||quantity<1000||quantity>50000||quantity%1000!==0)return json(res,400,{error:'Quantidade inválida.'});
 if(type==='Gamepass'){if(!validGamepassUrl(gamepassUrl))return json(res,400,{error:'Envie um link válido da Gamepass do Roblox.'})}else if(confirmRobloxName.toLowerCase()!==robloxUsername.toLowerCase())return json(res,400,{error:'Confirme exatamente o nome do Roblox para Robux Plus.'});
 stage='database-order';const amount=Number((quantity/1000*(type==='Gamepass'?26:40)).toFixed(2));
 const sessionClient=createClient(url,anonKey,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${token}`}}});
 const {data:order,error:orderError}=await sessionClient.from('orders').insert({user_id:user.id,robux:quantity,method:type,amount,roblox_username:robloxUsername,payer_name:name,payer_document:cpf,status:'PENDING',gamepass_url:type==='Gamepass'?gamepassUrl:null}).select('id,amount,status,created_at').single();
 if(orderError){console.error('create-order insert:',dbMessage(orderError));return json(res,500,{error:`Erro interno no banco (database-order): ${dbMessage(orderError)}`});}
 // Notification creation is performed with the authenticated user's session, not the service-role key.
 // This prevents checkout from failing just because a Vercel service-role environment variable is absent.
 const {error:notificationError}=await sessionClient.from('notifications').insert({user_id:user.id,title:'Pedido pendente',message:`Seu pedido de ${quantity.toLocaleString('pt-BR')} Robux foi criado e está aguardando pagamento.`,type:'order',order_id:order.id});if(notificationError)console.error('pending notification:',dbMessage(notificationError));
 stage='misticpay';const transactionId=String(order.id);const payload={amount,payerName:name,payerDocument:cpf,transactionId,description:`Best Robux - ${quantity} Robux - ${type}`};if(process.env.MISTICPAY_WEBHOOK_URL)payload.projectWebhook=process.env.MISTICPAY_WEBHOOK_URL;
 let response;try{response=await fetch('https://api.misticpay.com/api/transactions/create',{method:'POST',headers:misticHeaders(),body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});}catch(e){await sessionClient.rpc('set_order_payment',{p_order_id:order.id,p_status:'FAILED'});console.error('MisticPay request:',e);return json(res,502,{error:`Não foi possível conectar ao serviço de pagamento: ${e?.message||'falha de conexão'}`,orderId:order.id});}
 const payment=await response.json().catch(()=>({}));if(!response.ok){await sessionClient.rpc('set_order_payment',{p_order_id:order.id,p_status:'FAILED'});console.error('MisticPay response:',response.status,payment);return json(res,502,{error:payment?.message||payment?.error||`MisticPay retornou HTTP ${response.status}.`,orderId:order.id});}
 stage='payment-response';const data=payment?.data||payment,gatewayId=data.transactionId||data.id,copy=data.copyPaste||data.copy_paste,qr=data.qrCodeBase64||data.qr_code_base64||data.qrcodeUrl||data.qr_code;if(!gatewayId||(!copy&&!qr)){await sessionClient.rpc('set_order_payment',{p_order_id:order.id,p_status:'FAILED'});console.error('MisticPay invalid response:',payment);return json(res,502,{error:'A cobrança foi criada sem dados PIX válidos.',orderId:order.id});}
 stage='save-payment';const {data:saved,error:updateError}=await sessionClient.rpc('set_order_payment',{p_order_id:order.id,p_status:'PENDING',p_payment_transaction_id:String(gatewayId),p_pix_copy_paste:copy?String(copy):null,p_pix_qr_code:qr?String(qr):null});if(updateError){console.error('create-order update:',dbMessage(updateError));return json(res,500,{error:`Erro interno no banco (payment-save): ${dbMessage(updateError)}`,orderId:order.id});}return json(res,201,{order:{...order,status:saved?.status||order.status},payment:{transaction_id:String(gatewayId),copy_paste:copy?String(copy):null,qr_code:qr?String(qr):null}});
}catch(e){console.error('create-order:',stage,e);return json(res,500,{error:`Erro interno ao criar o pedido (${stage}): ${e?.message||'erro desconhecido'}`})}}
