import { createClient } from '@supabase/supabase-js';
const json=(res,s,b)=>res.status(s).json(b);const db=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_ANON_KEY,{auth:{persistSession:false}});const admin=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
async function auth(req){const t=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t)throw Error('AUTH');const {data,error}=await db().auth.getUser(t);if(error||!data.user)throw Error('AUTH');return data.user}
const money=v=>Math.round(Number(v)*100)/100;const key=()=>process.env.MARKETPLACE_STOCK_KEY||process.env.MARKETPLACE_ARCHIVE_KEY||'CHANGE_ME';
async function enc(v){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(key())),k=await crypto.subtle.importKey('raw',h,{name:'AES-GCM'},false,['encrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),c=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,new TextEncoder().encode(v));return Buffer.from(iv).toString('base64')+'.'+Buffer.from(c).toString('base64')}
export default async function handler(req,res){try{const a=admin();if(req.method==='GET'){const {data,error}=await a.from('marketplace_products').select('id,title,description,category,price,quantity,image_url,delivery_type,seller_id,created_at').eq('active',true).gt('quantity',0).order('created_at',{ascending:false});if(error)throw error;return json(res,200,{products:data||[]})}const user=await auth(req),b=req.body||{},action=String(b.action||'');
if(action==='create-product'){const {data:s}=await a.from('seller_applications').select('status').eq('user_id',user.id).eq('status','APPROVED').maybeSingle();if(!s)return json(res,403,{error:'Você ainda não foi aprovado como vendedor.'});const delivery=b.deliveryType==='DIGITAL'?'DIGITAL':'CHAT',q=delivery==='DIGITAL'?0:Number(b.quantity),price=money(b.price),title=String(b.title||'').trim();if(!title||price<=0||!Number.isInteger(q)||q<0)return json(res,400,{error:'Dados do produto inválidos.'});const {data,error}=await a.from('marketplace_products').insert({seller_id:user.id,title,description:String(b.description||''),category:String(b.category||'Outros'),price,quantity:q,image_url:b.imageUrl||null,delivery_type:delivery,active:delivery==='DIGITAL'?false:q>0}).select().single();if(error)throw error;return json(res,201,{product:data,needsStock:delivery==='DIGITAL'})}
if(action==='add-digital-stock'){const id=String(b.productId||''),items=(Array.isArray(b.items)?b.items:String(b.items||'').split(/\r?\n/)).map(x=>String(x).trim()).filter(Boolean);if(!id||!items.length)return json(res,400,{error:'Adicione pelo menos uma conta ao estoque.'});const {data:p}=await a.from('marketplace_products').select('id,seller_id,delivery_type,quantity').eq('id',id).maybeSingle();if(!p||p.seller_id!==user.id||p.delivery_type!=='DIGITAL')return json(res,403,{error:'Produto digital inválido.'});const rows=[];for(const item of items)rows.push({product_id:id,seller_id:user.id,payload_ciphertext:await enc(item),status:'AVAILABLE'});const {error}=await a.from('marketplace_digital_stock').insert(rows);if(error)throw error;const {error:ue}=await a.from('marketplace_products').update({quantity:Number(p.quantity||0)+items.length,active:true,updated_at:new Date().toISOString()}).eq('id',id);if(ue)throw ue;return json(res,201,{ok:true,added:items.length})}
if(action==='digital-stock'){const id=String(b.productId||'');const {data:p}=await a.from('marketplace_products').select('id,seller_id,delivery_type').eq('id',id).maybeSingle();if(!p||p.seller_id!==user.id||p.delivery_type!=='DIGITAL')return json(res,403,{error:'Sem acesso.'});const {data,error}=await a.from('marketplace_digital_stock').select('id,status,order_id,created_at').eq('product_id',id).order('created_at',{ascending:false});if(error)throw error;return json(res,200,{stock:data||[]})}
if(action==='my-products'){const {data,error}=await a.from('marketplace_products').select('*').eq('seller_id',user.id).order('created_at',{ascending:false});if(error)throw error;return json(res,200,{products:data||[]})}
if(action==='update-product'){const id=String(b.productId||''),price=money(b.price),q=Number(b.quantity);const {data:p}=await a.from('marketplace_products').select('id,seller_id').eq('id',id).maybeSingle();if(!p||p.seller_id!==user.id)return json(res,403,{error:'Você só pode editar seus próprios produtos.'});if(!String(b.title||'').trim()||price<=0||!Number.isInteger(q)||q<0)return json(res,400,{error:'Dados do produto inválidos.'});const {data,error}=await a.from('marketplace_products').update({title:String(b.title).trim(),description:String(b.description||''),category:String(b.category||'Outros'),price,quantity:q,image_url:b.imageUrl||null,delivery_type:b.deliveryType==='DIGITAL'?'DIGITAL':'CHAT',active:q>0,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return json(res,200,{product:data})}
if(action==='delete-product'){const id=String(b.productId||''),{data:p}=await a.from('marketplace_products').select('id,seller_id').eq('id',id).maybeSingle();if(!p||p.seller_id!==user.id)return json(res,403,{error:'Você só pode excluir seus próprios produtos.'});const {count}=await a.from('marketplace_orders').select('id',{count:'exact',head:true}).eq('product_id',id).not('status','in','(CANCELLED,REFUNDED)');if((count||0)>0)return json(res,409,{error:'Este produto possui pedidos e não pode ser excluído.'});const {error}=await a.from('marketplace_products').delete().eq('id',id);if(error)throw error;return json(res,200,{ok:true})}
if(action==='apply-seller'){const {error}=await a.from('seller_applications').upsert({user_id:user.id,full_name:String(b.fullName||''),birth_date:String(b.birthDate||''),cpf:String(b.cpf||'').replace(/\D/g,''),email:user.email||'',phone:String(b.phone||''),status:'PENDING',updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;return json(res,200,{ok:true})}
if(action==='seller-status'){const {data,error}=await a.from('seller_applications').select('status,rejection_reason,created_at,reviewed_at').eq('user_id',user.id).maybeSingle();if(error)throw error;return json(res,200,{application:data})}
if(action==='orders'){const {data,error}=await a.from('marketplace_orders').select('*, marketplace_products(title,image_url,delivery_type)').or(`buyer_id.eq.${user.id},seller_id.eq.${user.id}`).order('created_at',{ascending:false});if(error)throw error;return json(res,200,{orders:data||[]})}
if(action==='messages'){const id=String(b.orderId),{data:o}=await a.from('marketplace_orders').select('buyer_id,seller_id,status').eq('id',id).maybeSingle();if(!o||![o.buyer_id,o.seller_id].includes(user.id))return json(res,403,{error:'Sem acesso.'});const {data,error}=await a.from('marketplace_messages').select('id,sender_id,body,created_at').eq('order_id',id).order('created_at');if(error)throw error;return json(res,200,{messages:data||[],order:o})}
if(action==='message'){const id=String(b.orderId),body=String(b.body||'').trim();if(!body)return json(res,400,{error:'Mensagem vazia.'});const {data:o}=await a.from('marketplace_orders').select('buyer_id,seller_id').eq('id',id).maybeSingle();if(!o||![o.buyer_id,o.seller_id].includes(user.id))return json(res,403,{error:'Sem acesso.'});const {error}=await a.from('marketplace_messages').insert({order_id:id,sender_id:user.id,body});if(error)throw error;return json(res,201,{ok:true})}
return json(res,400,{error:'Ação inválida.'})}catch(e){console.error('marketplace',e);return json(res,e.message==='AUTH'?401:500,{error:e.message==='AUTH'?'Faça login novamente.':e.message||'Erro interno.'})}}