import { createClient } from '@supabase/supabase-js';
export const config={runtime:'nodejs'};
const json=(res,s,b)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');return res.status(s).json(b)};
const url=()=>process.env.SUPABASE_URL;
const anon=()=>createClient(url(),process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const admin=()=>createClient(url(),process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
async function auth(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();if(!token||token.length>8192)throw Error('AUTH');let r;try{r=await admin().auth.getUser(token)}catch{}if(!r?.data?.user){try{r=await anon().auth.getUser(token)}catch{}}if(r?.error||!r?.data?.user)throw Error('AUTH');return r.data.user}
const money=v=>Math.round(Number(v)*100)/100;
function stockKey(){const k=process.env.MARKETPLACE_STOCK_KEY||process.env.MARKETPLACE_ARCHIVE_KEY;if(!k||k==='CHANGE_ME_SET_A_REAL_SECRET')throw Error('MARKETPLACE_STOCK_KEY não configurada.');return k}
async function encryptText(text){if(text.length>4096)throw Error('Cada item digital deve ter no máximo 4096 caracteres.');const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(stockKey()));const key=await crypto.subtle.importKey('raw',hash,{name:'AES-GCM'},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(text));return `${Buffer.from(iv).toString('base64')}.${Buffer.from(cipher).toString('base64')}`}
async function mpCreate(amount,user,transactionId,description){const ci=process.env.MISTICPAY_CLIENT_ID,cs=process.env.MISTICPAY_CLIENT_SECRET;if(!ci||!cs)throw Error('Gateway de pagamento não configurado no servidor.');const r=await fetch('https://api.misticpay.com/api/transactions/create',{method:'POST',headers:{ci,cs,'Content-Type':'application/json'},body:JSON.stringify({amount,payerName:String(user.user_metadata?.full_name||user.email||'Cliente').slice(0,100),payerDocument:String(user.user_metadata?.cpf||'00000000000'),transactionId,description,projectWebhook:process.env.MISTICPAY_WEBHOOK_URL||`${process.env.SITE_URL||'https://bestrobux.vercel.app'}/api/misticpay-webhook`}),signal:AbortSignal.timeout(15000)});const x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x?.message||x?.error||'Falha ao criar pagamento PIX');const d=x?.data||x;if(!d?.transactionId)throw Error('Gateway não retornou o identificador do pagamento.');return {transactionId:String(d.transactionId),copyPaste:d.copyPaste||d.copy_paste||null,qrCode:d.qrCodeBase64||d.qr_code_base64||d.qrcodeUrl||null}}
export default async function handler(req,res){try{const a=admin();if(req.method==='GET'){const {data,error}=await a.from('marketplace_products').select('id,title,description,category,price,quantity,image_url,delivery_type,seller_id,created_at').eq('active',true).gt('quantity',0).order('created_at',{ascending:false}).limit(100);if(error)throw error;return json(res,200,{products:data||[]})}if(req.method!=='POST')return json(res,405,{error:'Método não permitido.'});const user=await auth(req),b=req.body||{},action=String(b.action||'');if(JSON.stringify(b).length>200000)return json(res,413,{error:'Requisição muito grande.'});
if(action==='buy'){const {data:p,error}=await a.from('marketplace_products').select('id,title,seller_id,price,quantity,delivery_type,active').eq('id',b.productId).eq('active',true).maybeSingle();if(error)throw error;if(!p)return json(res,404,{error:'Produto não encontrado.'});const qty=Number(b.quantity||1);if(!Number.isInteger(qty)||qty<1||qty>p.quantity||qty>100)return json(res,409,{error:'Quantidade indisponível.'});if(p.seller_id===user.id)return json(res,400,{error:'Você não pode comprar seu próprio produto.'});if(p.delivery_type==='DIGITAL'){const {count}=await a.from('marketplace_digital_stock').select('id',{count:'exact',head:true}).eq('product_id',p.id).eq('status','AVAILABLE');if((count||0)<qty)return json(res,409,{error:'Estoque digital insuficiente.'})}const subtotal=money(p.price*qty),fee=1;const {data:o,error:oe}=await a.from('marketplace_orders').insert({product_id:p.id,buyer_id:user.id,seller_id:p.seller_id,quantity:qty,unit_price:p.price,subtotal,platform_fee:fee}).select('id,product_id,buyer_id,seller_id,quantity,unit_price,subtotal,platform_fee,status,created_at').single();if(oe)throw oe;try{const pay=await mpCreate(subtotal+fee,user,`MK-${o.id}`,`BestRobux Marketplace - ${p.title}`);const {data:updated,error:ue}=await a.from('marketplace_orders').update({payment_transaction_id:pay.transactionId}).eq('id',o.id).eq('status','PENDING_PAYMENT').select('id,product_id,buyer_id,seller_id,quantity,unit_price,subtotal,platform_fee,status,created_at,payment_transaction_id').single();if(ue)throw ue;return json(res,201,{order:updated,payment:pay})}catch(e){await a.from('marketplace_orders').update({status:'CANCELLED',updated_at:new Date().toISOString()}).eq('id',o.id).eq('status','PENDING_PAYMENT');throw e}}
if(action==='orders'){const {data,error}=await a.from('marketplace_orders').select('id,product_id,buyer_id,seller_id,quantity,unit_price,subtotal,platform_fee,status,created_at,updated_at,marketplace_products(title,image_url,delivery_type)').or(`buyer_id.eq.${user.id},seller_id.eq.${user.id}`).order('created_at',{ascending:false}).limit(200);if(error)throw error;return json(res,200,{orders:data||[]})}
if(action==='wallet'){await a.from('wallet_accounts').upsert({user_id:user.id},{onConflict:'user_id',ignoreDuplicates:true});const [account,transactions]=await Promise.all([a.from('wallet_accounts').select('balance,updated_at').eq('user_id',user.id).maybeSingle(),a.from('wallet_transactions').select('id,type,amount,fee,reference_id,description,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)]);if(account.error)throw account.error;if(transactions.error)throw transactions.error;return json(res,200,{account:account.data||{balance:0},transactions:transactions.data||[]})}
return json(res,400,{error:'Ação inválida.'})}catch(e){console.error('marketplace',e);return json(res,e.message==='AUTH'?401:500,{error:e.message==='AUTH'?'Sua sessão expirou. Entre novamente.':e.message||'Erro interno.'})}}