import { createClient } from '@supabase/supabase-js';
const json=(res,s,b)=>res.status(s).json(b); const db=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_ANON_KEY,{auth:{persistSession:false}}); const admin=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
async function auth(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)throw new Error('AUTH');const a=db();const {data,error}=await a.auth.getUser(token);if(error||!data.user)throw new Error('AUTH');return {token,user:data.user,client:createClient(process.env.SUPABASE_URL,process.env.SUPABASE_ANON_KEY,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${token}`}}})}}
function money(v){return Math.round(Number(v)*100)/100}
async function payment(order,user,description){const amount=money(order.subtotal);const transactionId=`MK-${order.id}`;const mp=await fetch('https://api.misticpay.com/api/transactions/create',{method:'POST',headers:{ci:process.env.MISTICPAY_CLIENT_ID||'',cs:process.env.MISTICPAY_CLIENT_SECRET||'','Content-Type':'application/json'},body:JSON.stringify({amount,payerName:String(user.user_metadata?.full_name||user.email||'Cliente').slice(0,100),payerDocument:String(user.user_metadata?.cpf||'00000000000'),transactionId,description,projectWebhook:process.env.MISTICPAY_WEBHOOK_URL||`${process.env.SITE_URL||'https://bestrobux.vercel.app'}/api/misticpay-webhook`}),signal:AbortSignal.timeout(15000)});const r=await mp.json().catch(()=>({}));if(!mp.ok)throw new Error(r?.message||r?.error||'Falha no pagamento');const d=r?.data||r;if(!d?.transactionId)throw new Error('Pagamento sem transactionId');return {transactionId:String(d.transactionId),copyPaste:d.copyPaste||d.copy_paste||null,qrCode:d.qrCodeBase64||d.qr_code_base64||d.qrcodeUrl||null}}
export default async function handler(req,res){try{const {user,client}=await auth(req);const b=req.body||{};const action=String(b.action||'');
if(req.method==='GET'){const {data:products,error}=await client.from('marketplace_products').select('id,title,description,category,price,quantity,image_url,delivery_type,seller_id,created_at').eq('active',true).gt('quantity',0).order('created_at',{ascending:false});if(error)throw error;return json(res,200,{products:products||[]})}
if(action==='apply-seller'){const fullName=String(b.fullName||'').trim(),birthDate=String(b.birthDate||''),cpf=String(b.cpf||'').replace(/\D/g,''),phone=String(b.phone||'').trim();if(fullName.split(/\s+/).length<2||!birthDate||cpf.length!==11||phone.length<8)return json(res,400,{error:'Preencha corretamente todos os dados.'});const {error}=await client.from('seller_applications').upsert({user_id:user.id,full_name:fullName,birth_date:birthDate,cpf,email:user.email||String(b.email||''),phone,status:'PENDING',updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;return json(res,200,{ok:true})}
if(action==='seller-status'){const {data}=await client.from('seller_applications').select('status,rejection_reason,created_at,reviewed_at').eq('user_id',user.id).maybeSingle();return json(res,200,{application:data})}
if(action==='create-product'){const {data:s}=await client.from('seller_applications').select('status').eq('user_id',user.id).eq('status','APPROVED').maybeSingle();if(!s)return json(res,403,{error:'Você ainda não foi aprovado como vendedor.'});const title=String(b.title||'').trim(),description=String(b.description||'').trim(),category=String(b.category||'Outros'),price=money(b.price),quantity=Number(b.quantity);if(!title||price<=0||!Number.isInteger(quantity)||quantity<1)return json(res,400,{error:'Dados do produto inválidos.'});const {data,error}=await client.from('marketplace_products').insert({seller_id:user.id,title,description,category,price,quantity,image_url:b.imageUrl||null,delivery_type:b.deliveryType==='DIGITAL'?'DIGITAL':'CHAT'}).select().single();if(error)throw error;return json(res,201,{product:data})}
if(action==='buy'){const {data:p,error}=await client.from('marketplace_products').select('*').eq('id',b.productId).eq('active',true).maybeSingle();if(error)throw error;if(!p)return json(res,404,{error:'Produto não encontrado.'});const qty=Math.max(1,Number(b.quantity||1));if(!Number.isInteger(qty)||qty>p.quantity)return json(res,409,{error:'Quantidade indisponível.'});if(p.seller_id===user.id)return json(res,400,{error:'Você não pode comprar seu próprio produto.'});const subtotal=money(p.price*qty),fee=1;const {data:o,error:oe}=await client.from('marketplace_orders').insert({product_id:p.id,buyer_id:user.id,seller_id:p.seller_id,quantity:qty,unit_price:p.price,subtotal,platform_fee:fee}).select().single();if(oe)throw oe;const pay=await payment(o,user,`BestRobux Marketplace - ${p.title}`);const {data:updated,error:ue}=await client.from('marketplace_orders').update({payment_transaction_id:pay.transactionId}).eq('id',o.id).select().single();if(ue)throw ue;return json(res,201,{order:updated,payment:pay})}
if(action==='orders'){const {data,error}=await client.from('marketplace_orders').select('*, marketplace_products(title,image_url)').or(`buyer_id.eq.${user.id},seller_id.eq.${user.id}`).order('created_at',{ascending:false});if(error)throw error;return json(res,200,{orders:data||[]})}
if(action==='messages'){const orderId=String(b.orderId);const {data:o}=await client.from('marketplace_orders').select('buyer_id,seller_id,status').eq('id',orderId).maybeSingle();if(!o||![o.buyer_id,o.seller_id].includes(user.id))return json(res,403,{error:'Sem acesso.'});const {data,error}=await client.from('marketplace_messages').select('id,sender_id,body,created_at').eq('order_id',orderId).order('created_at');if(error)throw error;return json(res,200,{messages:data||[],order:o})}
if(action==='message'){const orderId=String(b.orderId),body=String(b.body||'').trim();if(!body)return json(res,400,{error:'Mensagem vazia.'});const {error}=await client.from('marketplace_messages').insert({order_id:orderId,sender_id:user.id,body});if(error)throw error;return json(res,201,{ok:true})}
if(action==='confirm'){const {error}=await client.rpc('confirm_marketplace_order',{order_id:String(b.orderId)});if(error)throw error;const {data:o}=await client.from('marketplace_orders').select('*').eq('id',b.orderId).single();if(o.status==='COMPLETED'){const a=admin();const {data:m}=await a.from('marketplace_messages').select('sender_id,body,created_at').eq('order_id',o.id).order('created_at');const plaintext=JSON.stringify({order:o,messages:m||[]});const enc=new TextEncoder().encode(plaintext);const keyMaterial=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(process.env.MARKETPLACE_ARCHIVE_KEY||'CHANGE_ME'));const key=await crypto.subtle.importKey('raw',keyMaterial,{name:'AES-GCM'},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc);const b64=x=>Buffer.from(x).toString('base64');await a.from('marketplace_chat_archives').upsert({order_id:o.id,ciphertext:`${b64(iv)}.${b64(cipher)}`},{onConflict:'order_id'});await a.from('marketplace_messages').delete().eq('order_id',o.id)}return json(res,200,{order:o})}
if(action==='wallet'){const {data:account}=await client.from('wallet_accounts').select('balance,updated_at').eq('user_id',user.id).maybeSingle();const {data:transactions}=await client.from('wallet_transactions').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);return json(res,200,{account:account||{balance:0},transactions:transactions||[]})}
if(action==='withdraw'){const amount=money(b.amount);const pixKey=String(b.pixKey||'').trim();if(amount<=0||!pixKey)return json(res,400,{error:'Informe valor e chave PIX.'});const {data:a}=await client.from('wallet_accounts').select('balance').eq('user_id',user.id).maybeSingle();if(!a||Number(a.balance)<amount+2)return json(res,409,{error:'Saldo insuficiente para o saque e a taxa de R$ 2,00.'});const {data:w,error}=await client.from('wallet_withdrawals').insert({user_id:user.id,amount,fee:2,pix_key:pixKey}).select().single();if(error)throw error;const {error:ue}=await client.from('wallet_accounts').update({balance:Number(a.balance)-amount-2,updated_at:new Date().toISOString()}).eq('user_id',user.id);if(ue)throw ue;await client.from('wallet_transactions').insert({user_id:user.id,type:'WITHDRAWAL',amount:-amount,fee:2,reference_id:w.id,description:'Solicitação de saque'});return json(res,201,{withdrawal:w})}
return json(res,400,{error:'Ação inválida.'})}catch(e){console.error('marketplace',e);return json(res,e.message==='AUTH'?401:500,{error:e.message==='AUTH'?'Faça login novamente.':e.message||'Erro interno.'})}}
