import { createClient } from '@supabase/supabase-js';
const json=(res,status,body)=>{res.setHeader('Cache-Control','no-store,max-age=0,must-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('X-Content-Type-Options','nosniff');return res.status(status).json(body)};
const service=()=>createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});
async function getUser(token){if(!token||token.length>8192)throw Error('AUTH');const {data,error}=await service().auth.getUser(token);if(error||!data?.user)throw Error('AUTH');return data.user}
const sum=(rows,field)=>rows.reduce((n,x)=>n+Number(x?.[field]||0),0),upper=x=>String(x||'').toUpperCase();
async function safe(q,fallback=[]){try{const r=await q;if(r.error){console.error('wallet optional query',r.error);return {data:fallback,error:null}}return r}catch(e){console.error('wallet optional query',e);return {data:fallback,error:null}}}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{error:'Método não permitido.'});try{const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim(),user=await getUser(token),db=service();let acc=await safe(db.from('wallet_accounts').select('balance,updated_at').eq('user_id',user.id).maybeSingle(),null);if(!acc.data){const created=await safe(db.from('wallet_accounts').insert({user_id:user.id}).select('balance,updated_at').single(),{balance:0,updated_at:null});acc=created}
const [deps,withs,tx,med]=await Promise.all([
safe(db.from('wallet_deposits').select('amount,fee,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)),
safe(db.from('wallet_withdrawals').select('amount,fee,status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)),
safe(db.from('wallet_transactions').select('id,type,amount,fee,reference_id,description,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)),
safe(db.from('med_cases').select('id,user_id,amount,status,reason,justification,review_reason,created_at,updated_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100))]);
const deposits=deps.data||[],withdrawals=withs.data||[],transactions=tx.data||[],medCases=med.data||[],balance=Number(acc.data?.balance||0);const pendingMed=sum(medCases.filter(x=>['AWAITING_JUSTIFICATION','UNDER_REVIEW'].includes(upper(x.status))),'amount'),pendingWithdrawals=sum(withdrawals.filter(x=>['PENDING','PROCESSING'].includes(upper(x.status))),'amount');
return json(res,200,{summary:{balance,available:Math.min(balance,balance-pendingMed-pendingWithdrawals),pending_med:pendingMed,pending_withdrawals:pendingWithdrawals,total_deposits:sum(deposits.filter(x=>upper(x.status)==='PAID'),'amount'),total_withdrawals:sum(withdrawals.filter(x=>upper(x.status)==='PAID'),'amount'),updated_at:acc.data?.updated_at||null},transactions,deposits,withdrawals,medCases})}catch(e){if(e.message!=='AUTH')console.error('wallet-summary',e);return json(res,e.message==='AUTH'?401:500,{error:e.message==='AUTH'?'Sua sessão expirou. Atualize a página ou entre novamente.':'Não foi possível carregar a carteira agora.'})}}
